/* ==========================================================================
   Ritma Records — product catalog & photo storage (Supabase)
   ==========================================================================
   Replaces the old Netlify Blobs version (ritma-products + ritma-images
   stores). Products live in the `products` table; photos live in the
   `ritma-records` Storage bucket, which is Public — so once uploaded, a
   photo gets a permanent public URL directly from Supabase and the
   product's image_url column just stores that URL. No separate
   product-image.js serving function needed anymore, unlike the Blobs
   version — Supabase Storage serves the file itself.

   IDs are auto-generated by Postgres now (`generated always as identity`)
   — no more hand-rolled nextProductId()/max+1 logic like the Blobs
   version needed.
   ========================================================================== */

const { getSupabaseClient } = require('./supabase');

const BUCKET_NAME = 'product-images';

function rowToProduct(row) {
  return {
    id: row.id,
    sku: row.sku,
    title: row.title,
    artist: row.artist,
    format: row.format,
    condition: row.condition,
    price: Number(row.price),
    stock: row.stock,
    genre: row.genre,
    year: row.year,
    description: row.description,
    img: row.image_url,
    imagePath: row.image_path
  };
}

function productToRow(product) {
  const row = {
    sku: product.sku,
    title: product.title,
    artist: product.artist,
    format: product.format,
    condition: product.condition,
    price: product.price,
    stock: product.stock,
    genre: product.genre,
    year: product.year,
    description: product.description
  };
  if (product.img !== undefined) row.image_url = product.img;
  if (product.imagePath !== undefined) row.image_path = product.imagePath;
  return row;
}

async function getAllProducts() {
  const supabase = getSupabaseClient();
  const { data, error } = await supabase.from('products').select('*').order('id');
  if (error) throw error;
  return data.map(rowToProduct);
}

async function getProduct(id) {
  const supabase = getSupabaseClient();
  const { data, error } = await supabase.from('products').select('*').eq('id', id).maybeSingle();
  if (error) throw error;
  return data ? rowToProduct(data) : null;
}

async function saveProduct(product) {
  const supabase = getSupabaseClient();
  const row = productToRow(product);

  if (product.id) {
    const { data, error } = await supabase.from('products').update(row).eq('id', product.id).select().single();
    if (error) throw error;
    return rowToProduct(data);
  }

  const { data, error } = await supabase.from('products').insert(row).select().single();
  if (error) throw error;
  return rowToProduct(data);
}

async function deleteProduct(id) {
  const supabase = getSupabaseClient();
  const existing = await getProduct(id);
  if (existing && existing.imagePath) {
    await supabase.storage.from(BUCKET_NAME).remove([existing.imagePath]);
  }
  const { error } = await supabase.from('products').delete().eq('id', id);
  if (error) throw error;
}

/**
 * Uploads a product photo and returns its public URL + storage path.
 * The path includes a timestamp, so every upload is a distinct file —
 * that's what busts browser/CDN caching automatically on a re-upload,
 * same idea as the old ?v= query param trick, just built into the path.
 */
async function saveImage(id, base64Data, contentType) {
  const supabase = getSupabaseClient();
  const buffer = Buffer.from(base64Data, 'base64');
  const ext = (contentType && contentType.split('/')[1]) || 'jpg';
  const path = `products/${id}-${Date.now()}.${ext}`;

  const { error: uploadError } = await supabase.storage
    .from(BUCKET_NAME)
    .upload(path, buffer, { contentType: contentType || 'image/jpeg', upsert: true });
  if (uploadError) throw uploadError;

  const { data } = supabase.storage.from(BUCKET_NAME).getPublicUrl(path);
  return { url: data.publicUrl, path };
}

module.exports = { getAllProducts, getProduct, saveProduct, deleteProduct, saveImage };
